<?php
// This file generated by script.
// You needn't to change it usually. 
return [
    'NAME' => 'freepanel',
    'HOSTNAME' => 'localhost',
    'PORT' => 3306,
    'USERNAME' => 'root',
    'PASSWORD' => '@MYSQL_PASSWORD@',
];
